## (1) Data Description 
The project will use two datasets, **`players.csv`** and **`sessions.csv`**, both describing player demographics, in-game behaviour, and engagement metrics from an online game.

- **`players.csv`** contains player-level information such as unique IDs, demographics (e.g., age, gender, region), and whether the player has **subscribed to a game-related newsletter**.
- **`sessions.csv`** records player activity during gameplay sessions, including metrics such as session duration, number of sessions, total playtime, number of actions, and purchase history.

Since the question is focus on the potential relation of player characteristics and subscribing to a game-related newsletter. We will mainly focus on the **`players.csv`** which contains all the important imformations. It has 7 valid variables and 2 variable without any data, 196 observatioons in total. Here is the detailed descriptiion:

- **experience**: category variable, describe the player's experience on game. Range is between "beginner", "regular", "veteran", "amateur" and "pro".
- **subscribe**: category variable, describe whether the player subscribe to a game-related newsletter or not.
- **hashedEmail**: nominal variable, record player's email
- **played_hours**: quantative value, record how many hours the player played.
- **name**: nominal variable, record players' name
- **gender**: category varibale, record players' gender
- **age**: quantative variable. record players' age
- **individualId**: No data
- **organizationName**: No data

And here is for the **`sessions.csv`**, 5 variables with 1535 observations:

- **hashedEmail**: nominal variable, record player's email
- **start_time**: time variable, record the time that player begin to play
- **end_time**: time variable, record the time that player end playing
- **original_start_time**: time variable, record the original time that player begin to play
- **original_end_time**: time variable, record the original time that player end playing

**Potential issues and considerations:**
- Skewed distributions in engagement variables.
- Potential class imbalance in the response variable (`subscribed_newsletter`), as non-subscribers are likely to dominate.

These datasets may have been collected from in-game logs and user profiles, which could introduce selection bias toward active players.

---

## (2) Question

**Research Question:**  
*What player characteristics and behaviours are most predictive of subscribing to a game-related newsletter, and how do these features differ between various player types?* 

The **response variable** is `subscribe` (True or False).  
**Explanatory variables** may include:
- age
- experience
- played hours
- gender

So the specific question is **can we predict "subscribe" with "age,experience,played hours,gender"**

We can identify which types of players are most likely to engage beyond gameplay (via newsletter subscription), providing insights for marketing and retention strategies. I plan to first clean up the data so that it only contains the response variable and explanatory so that it's ready for classification.

---

## (3) Exploratory Data Analysis and Visualization
The data player.csv could be load as follow:

In [2]:
import altair as alt
import numpy as np
import pandas as pd
url = "https://drive.google.com/uc?export=download&id=1Mw9vW0hjTJwRWx0bDXiSpYsO3gKogaPz"
players = pd.read_csv(url)
players.sample(10)

,experience,subscribe,hashedEmail,played_hours,name,gender,age,individualId,organizationName
125,Regular,True,c57fa94e436cf49a929d0168e47d26fec3d900b321775e...,18.5,Dante,Male,49,NaN,NaN
24,Amateur,True,119f01b9877fc5ea0073d05602a353b91c4b48e4cf02f4...,0.7,Hugo,Female,21,NaN,NaN
144,Beginner,True,9782452b8e41d1f140374eec34c84f464df6ed12e2777e...,23.7,Isla,Male,24,NaN,NaN
45,Beginner,False,fa7d496b2f74c51ec70395bd8397b49f97a3ce8d7ba7e0...,0.0,Umar,Male,24,NaN,NaN
189,Amateur,False,514ebbaa30f0d162127e065ab780892b7930cf8d75944d...,0.0,Orion,Male,17,NaN,NaN
145,Veteran,False,11006065e9412650e99eea4a4aaaf0399bc338006f85e8...,0.1,Callum,Male,19,NaN,NaN
77,Regular,True,e21a324ccf5c873bafe82e47d5137b36aa312ee4803eeb...,0.0,Faye,Male,17,NaN,NaN
66,Veteran,False,70db3a16ef58cf8bf6d8658c426ba4a5fcd7523a0abdd4...,0.1,Lana,Male,22,NaN,NaN
86,Amateur,False,9253d1969af1ff941ac9b2a4b2c61158932898827ac710...,0.0,Ziad,Two-Spirited,23,NaN,NaN
106,Regular,False,63139b524e44d156daf265875fb8078bb2b24d6b7520a3...,0.0,Elias,Male,23,NaN,NaN

Then we can wrangle the data so only the related variables left:

In [7]:
players = players[['subscribe', 'age', 'gender', 'experience', 'played_hours']]
players.sample(10)

     subscribe  age        gender experience  played_hours
183       True   22          Male    Amateur          32.0
151       True   17          Male    Amateur           0.0
72        True   17          Male    Veteran           0.0
11        True   17          Male        Pro           0.0
105       True   17          Male    Regular           0.0
133       True   17  Two-Spirited   Beginner           0.0
78        True   22    Non-binary    Regular           0.0
100       True   20          Male    Amateur           0.0
130       True   23          Male    Amateur          56.1
187       True   17          Male    Amateur           0.0

In [ ]:
Following are some simple graph of response variable and the explantory variable respectively.
subscription distribution by age:

In [12]:
alt.Chart(players).mark_point().encode(
    y='subscribe:N',
    x='age:Q',
    color='subscribe:N'
).properties(title='Age Distribution by Subscription Status')

alt.Chart(...)

We can see that almost all the age below 15 subscribed and the subscription distributed more on younger age.

subscription distribution by experience:

In [27]:
prop_chart = (
    alt.Chart(players)
    .mark_bar()
    .encode(
        x=alt.X('experience:N', title='Experience Level'),
        y=alt.Y('count()', stack='normalize', title='Proportion'),
        color=alt.Color('subscribe:N', title='Subscribed')
    )
    .properties(height=200, title='Proportion of Players Subscribed by Experience')
)
prop_chart

alt.Chart(...)

We can see that veteran is less possible to subscribe compare with other experience level player.

And here is the proportion of subscription for different

In [22]:
chart = (
    alt.Chart(players)
    .mark_bar()
    .encode(
        x=alt.X('gender:N', title='Gender'),
        y=alt.Y('count()', stack='normalize', title='Proportion of Players'),
        color=alt.Color('subscribe:N', title='Subscribed'),  
    )
    .properties(
        title='Proportion of Subscription Status by Gender'
    )
)
chart

alt.Chart(...)

We can see that Agender, other and female has relative high subscription rate.

Here is the subscription distribution on play hours.

In [23]:
alt.Chart(players).mark_point().encode(
    y='subscribe:N',
    x='played_hours:Q',
    color='subscribe:N'
).properties(title='Age Distribution by Subscription Status')

alt.Chart(...)

We can see that obiviously all the long time player subscribed.

Overall, the exploratory analysis suggests that age and total playtime are the most promising predictors for newsletter subscription, while experience level and gender show weaker relationships.

## (4) Methods and Plan

This project will use a **K-Nearest Neighbours (KNN)** classifier to predict whether a player subscribes to a game-related newsletter based on their **age**, **played hours**, **experience**, and **gender**.

**Why KNN:**  
KNN is suitable for categorical prediction and does not rely on distributional assumptions. It classifies players based on similarity, making it intuitive for behavioural data.

**Assumptions & Limitations:**  
KNN assumes meaningful distance between samples and equal feature scales. It may perform poorly if categorical variables (e.g., experience, gender) are not properly encoded or if the data are imbalanced.

**Data Processing Plan:**  
- Split data: **75% training**, **25% testing**.  
- Encode categorical variables and **standardize** numeric ones.  
- Use **5-fold cross-validation** on the training data to find the best *k*.  
- Evaluate performance on the test set using **accuracy**, **precision**, and **recall**.

This approach balances simplicity, interpretability, and predictive reliability.

In this project, we applied a K-Nearest Neighbours (KNN) classifier to investigate which player characteristics are most associated with subscribing to a game-related newsletter. To prepare the data for modelling, we first loaded the player dataset and selected only the variables relevant to our analysis: age, played_hours, and subscribe. We cleaned and organized the data into a tidy format, removed missing values, and generated summary statistics and visualizations to understand the distributions of the key features.
Because KNN relies on distance calculations, we standardized the numerical variables (age and played_hours) to place them on comparable scales. The dataset was then split into training and testing sets (75/25) to allow for out-of-sample evaluation. A preprocessing pipeline was constructed using StandardScaler along with the KNN classifier, and cross-validation was used to tune the number of neighbors and assess model stability.
This method provides a clear and interpretable framework for examining how demographic and behavioural variables relate to subscription behaviour.

In [27]:
url = "https://drive.google.com/uc?export=download&id=1Mw9vW0hjTJwRWx0bDXiSpYsO3gKogaPz"
players = pd.read_csv(url)
players.sample(10)

,experience,subscribe,hashedEmail,played_hours,name,gender,age,individualId,organizationName
20,Regular,True,bc704ff2bc676dbf48ee41b9e11481c1387bf758ad318f...,0.3,Andy,Male,8,NaN,NaN
47,Regular,False,453774822d52d6891593948224570a750c4334616ff8aa...,0.0,Edmund,Prefer not to say,23,NaN,NaN
73,Veteran,True,a56b4b044e562fcf7765387d53c9e6543c42595fb43186...,0.0,Hadi,Male,22,NaN,NaN
190,Amateur,True,644fe4200c19a73768b3fa598afcbd0948f7557925b7f1...,0.0,Rhys,Male,20,NaN,NaN
114,Beginner,True,ae8d8a9dcf80b38466f89466201e6d594eb94d6994eda1...,1.0,Ella,Female,17,NaN,NaN
132,Regular,False,ba9b943f7fd9b5078b20ece741c4cb6435418d5d8373b4...,0.1,Daisy,Prefer not to say,17,NaN,NaN
162,Pro,True,f4f29f2465743ead8c3ce02fc84542afe33ae3c95ef56a...,0.6,Arlo,Male,19,NaN,NaN
109,Amateur,True,fe218a05c6c3fc6326f4f151e8cb75a2a9fa29e22b110d...,0.1,Fatima,Male,17,NaN,NaN
84,Beginner,True,cb3c5734effd1e0218ba26ed8f3e515149824105c76bbf...,0.0,Zara,Female,17,NaN,NaN
1,Veteran,True,f3c813577c458ba0dfef80996f8f32c93b6e8af1fa9397...,3.8,Christian,Male,17,NaN,NaN

In [17]:
alt.Chart(player_selected).mark_boxplot().encode(
    x=alt.X("subscribe:N").title("Subscription Status"),
    y=alt.Y("age:Q").title("Age"),
    color="subscribe:N"
).properties(
    title="Figure 1. Age Distribution by Subscription Status"
)

alt.Chart(...)

In [14]:
player_selected = players[["subscribe","played_hours","age"]]
player_selected

     subscribe  played_hours  age
0         True          30.3    9
1         True           3.8   17
2        False           0.0   17
3         True           0.7   21
4         True           0.1   21
..         ...           ...  ...
191       True           0.0   17
192      False           0.3   22
193      False           0.0   17
194      False           2.3   17
195       True           0.2   91

[196 rows x 3 columns]

From the visualization, subscribers and non-subscribers appear to have very similar age distributions.
Both groups mainly fall between their late teens and mid-20s, and their medians are almost identical.
There are a few older players in the dataset, but they do not seem to disproportionately subscribe or avoid subscribing.


Conclusion:
Age does not seem to be a strong predictor of newsletter subscription.
The overlap between the two groups suggests that players of different ages behave similarly in terms of subscribing.

In [11]:
alt.Chart(player_selected).mark_boxplot().encode(
    x="subscribe:N",
    y="played_hours:Q",
    color="subscribe:N"
).properties(
    title="Figure 2. Played Hours by Subscription Status"
)

alt.Chart(...)

Before fitting the KNN classifier, we applied preprocessing steps to prepare the dataset for modelling. Numerical variables were standardized to ensure equal scaling, and categorical variables were one-hot encoded so that KNN could compute meaningful distances across samples.

In [25]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import StandardScaler
layer_preprocessor = make_column_transformer(
    (StandardScaler(), ["played_hours", "age"]),
)

In [26]:
from sklearn.model_selection import train_test_split
import numpy as np

np.random.seed(1)

player_train, player_test = train_test_split(
    player_selected,
    train_size=0.75,
    stratify=player_selected["subscribe"]
)

player_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 147 entries, 20 to 127
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   subscribe     147 non-null    bool
 1   played_hours  147 non-null    float64
 2   age           147 non-null    int64
dtypes: bool(1), float64(1), int64(1)
memory usage: 3.6 KB